[project]
name = "hamilton-polars-pandera"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandera[polars]>=0.20.4",
    "sf-hamilton[lsp,pandera]>=1.80.0",
]
